# Generated by Django 4.2.7 on 2023-11-05 03:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Homeowner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(default='Not provided', max_length=255)),
                ('phone_number', models.CharField(default='Not provided', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('sign_up_date', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homeowner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
