# Generated by Django 4.2.7 on 2023-11-05 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeowner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255, verbose_name='Home Address')),
                ('mortgage_details', models.TextField(blank=True, null=True, verbose_name='Mortgage Details')),
                ('insurance_details', models.TextField(blank=True, null=True, verbose_name='Insurance Details')),
                ('lawn_size', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Lawn Size')),
                ('flower_bed_size', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Flower Bed Size')),
                ('number_of_trees', models.IntegerField(default=0, verbose_name='Number of Trees')),
                ('internet_service_provider', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_plan', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_speed', models.CharField(blank=True, max_length=255, null=True)),
                ('internet_contract_renewal_date', models.DateField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Homeowner',
        ),
    ]
