# Generated by Django 4.2.7 on 2023-11-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0002_home_profile_delete_homeowner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='internet_contract_renewal_date',
            new_name='internet_contract_end_date',
        ),
    ]
