# Generated by Django 4.2.7 on 2023-11-06 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0003_rename_internet_contract_renewal_date_home_internet_contract_end_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='insurance_details',
        ),
        migrations.RemoveField(
            model_name='home',
            name='mortgage_details',
        ),
        migrations.AddField(
            model_name='home',
            name='insurance_coverage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='insurance_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='insurance_policy_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='insurance_premium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='insurance_provider',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='insurance_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mortgage_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mortgage_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mortgage_lender',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mortgage_monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='home',
            name='mortgage_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
