# Generated by Django 4.2.7 on 2023-11-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0004_remove_home_insurance_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='floor_plan',
            field=models.ImageField(blank=True, null=True, upload_to='floor_plans/'),
        ),
        migrations.AddField(
            model_name='home',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Bathrooms'),
        ),
        migrations.AddField(
            model_name='home',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Bedrooms'),
        ),
        migrations.AddField(
            model_name='home',
            name='number_of_living_rooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Number of Living Rooms'),
        ),
        migrations.AddField(
            model_name='home',
            name='total_floor_space',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Floor Space (sqft)'),
        ),
        migrations.AlterField(
            model_name='home',
            name='lawn_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Area of Lawn (sqft)'),
        ),
    ]
