# Generated by Django 4.2.7 on 2023-11-09 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0005_home_floor_plan_home_number_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='number_of_bathrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Bathrooms'),
        ),
        migrations.AlterField(
            model_name='home',
            name='number_of_bedrooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Bedrooms'),
        ),
        migrations.AlterField(
            model_name='home',
            name='number_of_living_rooms',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Living Rooms'),
        ),
    ]
