# Generated by Django 4.2.7 on 2023-11-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0006_alter_home_number_of_bathrooms_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='internet_speed',
            new_name='current_internet_speed',
        ),
        migrations.AddField(
            model_name='home',
            name='recommended_internet_speed',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='number_of_phones',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Number of Phones'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_plan_contract_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Contract End Date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_plan_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly Cost'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_plan_data_limit',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Data Limit'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_plan_provider',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Phone Plan Provider'),
        ),
    ]
