# Generated by Django 4.2.7 on 2023-11-24 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0007_rename_internet_speed_home_current_internet_speed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='internet_plan',
            new_name='internet_monthly_payment',
        ),
    ]
