# Generated by Django 4.2.7 on 2023-12-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0011_profile_business_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='business_type',
            field=models.CharField(blank=True, choices=[('Internet', 'Internet Service Provider'), ('Landscaping', 'Landscaping Services'), ('PhonePlans', 'Phone Plan Services')], max_length=50, null=True, verbose_name='Business Type'),
        ),
    ]
