# Generated by Django 4.2.7 on 2023-12-05 04:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0012_profile_business_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(default='BadAddress', max_length=255, verbose_name='Business Address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='zip_code',
            field=models.PositiveIntegerField(default=11111, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='Zip Code'),
        ),
    ]
