# Generated by Django 4.2.7 on 2023-12-05 04:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0013_profile_address_profile_zip_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='zip_code',
            field=models.PositiveIntegerField(default=11111, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='Zip Code'),
        ),
    ]
