# Generated by Django 4.2.7 on 2023-12-05 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0014_home_zip_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address',
            new_name='business_address',
        ),
    ]
