# Generated by Django 4.2.7 on 2023-12-05 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0016_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('business', models.ForeignKey(limit_choices_to={'user_type': 'business'}, on_delete=django.db.models.deletion.CASCADE, to='homeowner.profile')),
            ],
        ),
    ]
