# Generated by Django 4.2.7 on 2023-12-06 07:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homeowner', '0019_profile_is_business_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_code', models.CharField(max_length=5)),
                ('deal_type', models.CharField(choices=[('internet', 'Internet')], max_length=10)),
                ('provider_name', models.CharField(max_length=255)),
                ('internet_speed_offered', models.PositiveIntegerField()),
                ('monthly_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deal_expiration_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
