# Generated by Django 4.2.7 on 2023-12-07 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0020_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='internet_price_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='homeowner.deal'),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('deal', 'Deal'), ('system', 'System')], default='system', max_length=10),
        ),
    ]
