# Generated by Django 4.2.7 on 2023-12-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0022_alter_home_current_internet_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='current_internet_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='recommended_internet_speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
