# Generated by Django 4.2.7 on 2023-12-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0023_alter_home_current_internet_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='internet_monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
