# Generated by Django 4.2.7 on 2023-12-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0024_alter_home_internet_monthly_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='internet_price_threshold',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=6),
            preserve_default=False,
        ),
    ]
