# Generated by Django 4.2.7 on 2023-12-07 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0026_home_landscaping_service_needed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='landscaping_service_needed',
        ),
        migrations.CreateModel(
            name='LandscapingServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('lawn_mowing', 'Lawn Mowing'), ('tree_trimming', 'Tree Trimming'), ('lawn_care', 'Lawn Care')], max_length=50)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('home', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landscaping_requests', to='homeowner.home')),
            ],
        ),
    ]
