# Generated by Django 4.2.7 on 2023-12-08 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0029_landscapingservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='internet_price_threshold',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
