# Generated by Django 4.2.7 on 2023-12-10 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0030_alter_home_internet_price_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='zip_code',
            field=models.PositiveIntegerField(default=11111, validators=[django.core.validators.MaxValueValidator(99999), django.core.validators.MinValueValidator(10000)], verbose_name='Zip Code'),
        ),
    ]
