# Generated by Django 4.2.7 on 2023-12-10 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0031_alter_business_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='deal_expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
