# Generated by Django 4.2.7 on 2023-12-11 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homeowner', '0033_alter_deal_deal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOpportunityReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_data', models.TextField()),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunity_reports', to='homeowner.business')),
            ],
        ),
    ]
